/* automatically generated by rust-bindgen 0.72.1 */
#![allow(nonstandard_style, dead_code)]

pub const _TIME_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2Y: u32 = 0;
pub const __GLIBC_USE_ISOC23: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 202405;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __USE_XOPEN2K24: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_TIME_BITS64: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 43;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const _BITS_TIME_H: u32 = 1;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const CLOCK_REALTIME: u32 = 0;
pub const CLOCK_MONOTONIC: u32 = 1;
pub const CLOCK_PROCESS_CPUTIME_ID: u32 = 2;
pub const CLOCK_THREAD_CPUTIME_ID: u32 = 3;
pub const CLOCK_MONOTONIC_RAW: u32 = 4;
pub const CLOCK_REALTIME_COARSE: u32 = 5;
pub const CLOCK_MONOTONIC_COARSE: u32 = 6;
pub const CLOCK_BOOTTIME: u32 = 7;
pub const CLOCK_REALTIME_ALARM: u32 = 8;
pub const CLOCK_BOOTTIME_ALARM: u32 = 9;
pub const CLOCK_TAI: u32 = 11;
pub const TIMER_ABSTIME: u32 = 1;
pub const __clock_t_defined: u32 = 1;
pub const __time_t_defined: u32 = 1;
pub const __struct_tm_defined: u32 = 1;
pub const _STRUCT_TIMESPEC: u32 = 1;
pub const _BITS_ENDIAN_H: u32 = 1;
pub const __LITTLE_ENDIAN: u32 = 1234;
pub const __BIG_ENDIAN: u32 = 4321;
pub const __PDP_ENDIAN: u32 = 3412;
pub const _BITS_ENDIANNESS_H: u32 = 1;
pub const __BYTE_ORDER: u32 = 1234;
pub const __FLOAT_WORD_ORDER: u32 = 1234;
pub const __clockid_t_defined: u32 = 1;
pub const __timer_t_defined: u32 = 1;
pub const __itimerspec_defined: u32 = 1;
pub const _BITS_TYPES_LOCALE_T_H: u32 = 1;
pub const _BITS_TYPES___LOCALE_T_H: u32 = 1;
pub const TIME_UTC: u32 = 1;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::std::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::std::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::std::mem::offset_of!(__fsid_t, __val) - 0usize];
};
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type clock_t = __clock_t;
pub type time_t = __time_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tm {
    pub tm_sec: ::std::os::raw::c_int,
    pub tm_min: ::std::os::raw::c_int,
    pub tm_hour: ::std::os::raw::c_int,
    pub tm_mday: ::std::os::raw::c_int,
    pub tm_mon: ::std::os::raw::c_int,
    pub tm_year: ::std::os::raw::c_int,
    pub tm_wday: ::std::os::raw::c_int,
    pub tm_yday: ::std::os::raw::c_int,
    pub tm_isdst: ::std::os::raw::c_int,
    pub tm_gmtoff: ::std::os::raw::c_long,
    pub tm_zone: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tm"][::std::mem::size_of::<tm>() - 56usize];
    ["Alignment of tm"][::std::mem::align_of::<tm>() - 8usize];
    ["Offset of field: tm::tm_sec"][::std::mem::offset_of!(tm, tm_sec) - 0usize];
    ["Offset of field: tm::tm_min"][::std::mem::offset_of!(tm, tm_min) - 4usize];
    ["Offset of field: tm::tm_hour"][::std::mem::offset_of!(tm, tm_hour) - 8usize];
    ["Offset of field: tm::tm_mday"][::std::mem::offset_of!(tm, tm_mday) - 12usize];
    ["Offset of field: tm::tm_mon"][::std::mem::offset_of!(tm, tm_mon) - 16usize];
    ["Offset of field: tm::tm_year"][::std::mem::offset_of!(tm, tm_year) - 20usize];
    ["Offset of field: tm::tm_wday"][::std::mem::offset_of!(tm, tm_wday) - 24usize];
    ["Offset of field: tm::tm_yday"][::std::mem::offset_of!(tm, tm_yday) - 28usize];
    ["Offset of field: tm::tm_isdst"][::std::mem::offset_of!(tm, tm_isdst) - 32usize];
    ["Offset of field: tm::tm_gmtoff"][::std::mem::offset_of!(tm, tm_gmtoff) - 40usize];
    ["Offset of field: tm::tm_zone"][::std::mem::offset_of!(tm, tm_zone) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec {
    pub tv_sec: __time_t,
    pub tv_nsec: __syscall_slong_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of timespec"][::std::mem::size_of::<timespec>() - 16usize];
    ["Alignment of timespec"][::std::mem::align_of::<timespec>() - 8usize];
    ["Offset of field: timespec::tv_sec"][::std::mem::offset_of!(timespec, tv_sec) - 0usize];
    ["Offset of field: timespec::tv_nsec"][::std::mem::offset_of!(timespec, tv_nsec) - 8usize];
};
pub type clockid_t = __clockid_t;
pub type timer_t = __timer_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct itimerspec {
    pub it_interval: timespec,
    pub it_value: timespec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of itimerspec"][::std::mem::size_of::<itimerspec>() - 32usize];
    ["Alignment of itimerspec"][::std::mem::align_of::<itimerspec>() - 8usize];
    ["Offset of field: itimerspec::it_interval"]
        [::std::mem::offset_of!(itimerspec, it_interval) - 0usize];
    ["Offset of field: itimerspec::it_value"]
        [::std::mem::offset_of!(itimerspec, it_value) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sigevent {
    _unused: [u8; 0],
}
pub type pid_t = __pid_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __locale_struct {
    pub __locales: [*mut __locale_data; 13usize],
    pub __ctype_b: *const ::std::os::raw::c_ushort,
    pub __ctype_tolower: *const ::std::os::raw::c_int,
    pub __ctype_toupper: *const ::std::os::raw::c_int,
    pub __names: [*const ::std::os::raw::c_char; 13usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __locale_struct"][::std::mem::size_of::<__locale_struct>() - 232usize];
    ["Alignment of __locale_struct"][::std::mem::align_of::<__locale_struct>() - 8usize];
    ["Offset of field: __locale_struct::__locales"]
        [::std::mem::offset_of!(__locale_struct, __locales) - 0usize];
    ["Offset of field: __locale_struct::__ctype_b"]
        [::std::mem::offset_of!(__locale_struct, __ctype_b) - 104usize];
    ["Offset of field: __locale_struct::__ctype_tolower"]
        [::std::mem::offset_of!(__locale_struct, __ctype_tolower) - 112usize];
    ["Offset of field: __locale_struct::__ctype_toupper"]
        [::std::mem::offset_of!(__locale_struct, __ctype_toupper) - 120usize];
    ["Offset of field: __locale_struct::__names"]
        [::std::mem::offset_of!(__locale_struct, __names) - 128usize];
};
pub type __locale_t = *mut __locale_struct;
pub type locale_t = __locale_t;
unsafe extern "C" {
    pub fn clock() -> clock_t;
}
unsafe extern "C" {
    pub fn time(__timer: *mut time_t) -> time_t;
}
unsafe extern "C" {
    pub fn difftime(__time1: time_t, __time0: time_t) -> f64;
}
unsafe extern "C" {
    pub fn mktime(__tp: *mut tm) -> time_t;
}
unsafe extern "C" {
    pub fn strftime(
        __s: *mut ::std::os::raw::c_char,
        __maxsize: usize,
        __format: *const ::std::os::raw::c_char,
        __tp: *const tm,
    ) -> usize;
}
unsafe extern "C" {
    pub fn strftime_l(
        __s: *mut ::std::os::raw::c_char,
        __maxsize: usize,
        __format: *const ::std::os::raw::c_char,
        __tp: *const tm,
        __loc: locale_t,
    ) -> usize;
}
unsafe extern "C" {
    pub fn gmtime(__timer: *const time_t) -> *mut tm;
}
unsafe extern "C" {
    pub fn localtime(__timer: *const time_t) -> *mut tm;
}
unsafe extern "C" {
    pub fn gmtime_r(__timer: *const time_t, __tp: *mut tm) -> *mut tm;
}
unsafe extern "C" {
    pub fn localtime_r(__timer: *const time_t, __tp: *mut tm) -> *mut tm;
}
unsafe extern "C" {
    pub fn asctime(__tp: *const tm) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn ctime(__timer: *const time_t) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn asctime_r(
        __tp: *const tm,
        __buf: *mut ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn ctime_r(
        __timer: *const time_t,
        __buf: *mut ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub static mut __tzname: [*mut ::std::os::raw::c_char; 2usize];
}
unsafe extern "C" {
    pub static mut __daylight: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut __timezone: ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub static mut tzname: [*mut ::std::os::raw::c_char; 2usize];
}
unsafe extern "C" {
    pub fn tzset();
}
unsafe extern "C" {
    pub static mut daylight: ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut timezone: ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn timegm(__tp: *mut tm) -> time_t;
}
unsafe extern "C" {
    pub fn timelocal(__tp: *mut tm) -> time_t;
}
unsafe extern "C" {
    pub fn dysize(__year: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn nanosleep(
        __requested_time: *const timespec,
        __remaining: *mut timespec,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn clock_getres(__clock_id: clockid_t, __res: *mut timespec) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn clock_gettime(__clock_id: clockid_t, __tp: *mut timespec) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn clock_settime(__clock_id: clockid_t, __tp: *const timespec) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn clock_nanosleep(
        __clock_id: clockid_t,
        __flags: ::std::os::raw::c_int,
        __req: *const timespec,
        __rem: *mut timespec,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn clock_getcpuclockid(__pid: pid_t, __clock_id: *mut clockid_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn timer_create(
        __clock_id: clockid_t,
        __evp: *mut sigevent,
        __timerid: *mut timer_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn timer_delete(__timerid: timer_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn timer_settime(
        __timerid: timer_t,
        __flags: ::std::os::raw::c_int,
        __value: *const itimerspec,
        __ovalue: *mut itimerspec,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn timer_gettime(__timerid: timer_t, __value: *mut itimerspec) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn timer_getoverrun(__timerid: timer_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn timespec_get(
        __ts: *mut timespec,
        __base: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a user successfully login to the server (/login).\n When you log in (/login) you should also receive from the server this event.\n @param user_uuid The id of the user who logged in\n @param user_name The name of the user who logged in\n\n Commands:\n /login \"user_name\""]
    pub fn client_event_logged_in(
        user_uuid: *const ::std::os::raw::c_char,
        user_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a user logged out (/logout or lost connexion).\n When you log out (/logout) you should also receive the event before quitting.\n @param user_uuid The id of the user who logged out\n @param user_name The name of the user who logged out\n\n Commands:\n /logout"]
    pub fn client_event_logged_out(
        user_uuid: *const ::std::os::raw::c_char,
        user_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when the current logged user receives a private message\n @param user_uuid The id of the user that sent the private message\n @param message_body The body of the private message\n\n Commands:\n /send \"user_uuid\" \"message_body\""]
    pub fn client_event_private_message_received(
        user_uuid: *const ::std::os::raw::c_char,
        message_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a new reply is posted in a thread\n @param team_uuid The id of the team this reply is in\n @param thread_uuid The id of the thread this reply is in\n @param user_uuid The id of the user that created the reply\n @param reply_body The reply body\n\n Commands:\n /create \"reply_body\""]
    pub fn client_event_thread_reply_received(
        team_uuid: *const ::std::os::raw::c_char,
        thread_uuid: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
        reply_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a new team is created\n Every logged user should receive this event (the creator of the team too)\n @param team_uuid The id of the created team\n @param team_name The name of the created team\n @param team_description The description of the created team\n\n Commands:\n /create \"team_name\" \"team_description\""]
    pub fn client_event_team_created(
        team_uuid: *const ::std::os::raw::c_char,
        team_name: *const ::std::os::raw::c_char,
        team_description: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a channel is created inside of a team\n @param channel_uuid The id of the created channel\n @param channel_name The name of the created channel\n @param channel_description The description of the created channel\n\n Commands:\n /create \"channel_name\" \"channel_description\""]
    pub fn client_event_channel_created(
        channel_uuid: *const ::std::os::raw::c_char,
        channel_name: *const ::std::os::raw::c_char,
        channel_description: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a thread is created inside of a channel\n @param thread_uuid The id of the created thread\n @param user_uuid The id of the user who created the thread\n @param thread_timestamp The unix timestamp of the thread creation\n @param thread_title The title of the created thread\n @param thread_body The body of the created thread\n\n Commands:\n /create \"thread_title\" \"thread_body\""]
    pub fn client_event_thread_created(
        thread_uuid: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
        thread_timestamp: time_t,
        thread_title: *const ::std::os::raw::c_char,
        thread_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you requested a list of users from the server\n ex: asking the subscribed users to a team / the list of users in a domain\n This function should be called once per user in the list\n This function should be called even if the list only has one entry\n @param user_uuid The id of a user\n @param user_name The name of a user\n @param user_status The status of a user (0: not connected; 1: connected)\n user_status is NOT the number of simultaneous connexion of a user\n\n Commands:\n /users\n /subscribed \"team_uuid\""]
    pub fn client_print_users(
        user_uuid: *const ::std::os::raw::c_char,
        user_name: *const ::std::os::raw::c_char,
        user_status: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you requested a list of teams from the server\n ex: asking the teams you are subscribed to or the available teams in a domain\n This function should be called once per team in the list\n This function should be called even if the list only has one entry\n @param team_uuid The id of a team\n @param team_name The name of a team\n @param team_description The description of a team\n\n Commands:\n /list\n /subscribed"]
    pub fn client_print_teams(
        team_uuid: *const ::std::os::raw::c_char,
        team_name: *const ::std::os::raw::c_char,
        team_description: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you requested a list of channels from the server\n ex: asking the channels in a team\n This function should be called one per channel in the list\n This function should be called even if the list only has one entry\n @param channel_uuid The id of a channel\n @param channel_name The name of a channel\n @param channel_description The description of a channel\n\n Commands:\n /list"]
    pub fn client_team_print_channels(
        channel_uuid: *const ::std::os::raw::c_char,
        channel_name: *const ::std::os::raw::c_char,
        channel_description: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you requested a list of threads from the server\n ex: asking the threads in a channel\n This function should be called one per thread in the list\n This function should be called even if the list only has one entry\n @param thread_uuid The id of a thread\n @param user_uuid The id of the user who created a thread\n @param thread_timestamp The unix timestamp of a thread creation\n @param thread_title The title of a thread\n @param thread_body The body of a thread\n\n Commands:\n /list"]
    pub fn client_channel_print_threads(
        thread_uuid: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
        thread_timestamp: time_t,
        thread_title: *const ::std::os::raw::c_char,
        thread_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you requested a list of replies from the server\n ex: asking the replies in a thread\n This function should be called one per reply in the list\n This function should be called even if the list only has one entry\n @param thread_uuid The id of the thread a reply belongs to\n @param user_uuid The id of the user who created a reply\n @param reply_timestamp The unix timestamp of a reply creation\n @param reply_body The body of a reply\n\n Commands:\n /list"]
    pub fn client_thread_print_replies(
        thread_uuid: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
        reply_timestamp: time_t,
        reply_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you requested a list of private messages\n ex: asking the private messages with a user\n This function should be called one per private  message in the list\n This function should be called even if the list only has one entry\n @param sender_uuid The id of the user who sent a private message\n @param message_timestamp The unix timestamp of a private message creation\n @param message_body The content of a private message\n\n Commands:\n /messages \"user_uuid\""]
    pub fn client_private_message_print_messages(
        sender_uuid: *const ::std::os::raw::c_char,
        message_timestamp: time_t,
        message_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when the user try to do an action\n with a team that does not exist (list channels, subscribe, etc...)\n @param team_uuid The id that was given and does not exist\n\n Commands:\n /subscribe \"team_uuid\"\n /unsubscribe \"team_uuid\"\n /subscribed \"team_uuid\"\n /list\n /create \"channel_name\" \"channel_description\"\n /create \"thread_title\" \"thread_body\"\n /create \"reply_body\"\n /info"]
    pub fn client_error_unknown_team(
        team_uuid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when the user try to do an action\n with a channel that does not exist (list threads, create thread, etc...)\n @param channel_uuid The id that was given and does not exist\n\n Commands:\n /list\n /create \"thread_title\" \"thread_body\"\n /create \"reply_body\"\n /info"]
    pub fn client_error_unknown_channel(
        channel_uuid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when the user try to do an action\n with a thread that does not exist (list replies, create reply, etc...)\n @param thread_uuid The id that was given and does not exist\n\n Commands:\n /list\n /create \"reply_body\"\n /info"]
    pub fn client_error_unknown_thread(
        thread_uuid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when the user try to do an action\n with a user that does not exist (send private message, /user)\n @param user_uuid The id that was given and does not exist\n\n Commands:\n /send \"user_uuid\" \"message_body\"\n /user \"user_uuid\"\n /messages \"user_uuid\""]
    pub fn client_error_unknown_user(
        user_uuid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when the user try to do an action he is not allowed\n to perform.\n Ex: create a thread in a team he is not subscribed\n Ex: create a team when he is not logged in\n\n Commands:\n Everything except /login"]
    pub fn client_error_unauthorized() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when the user try to do an action and the resource\n already exist.\n Ex: create a team with a name that already exist\n This error based itself on the name/title of the object created\n\n Commands:\n /create \"team_name\" \"team_description\"\n /create \"channel_name\" \"channel_description\"\n /create \"thread_title\" \"thread_body\""]
    pub fn client_error_already_exist() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you requested an individual user\n ex: get the current logged user, get information about a user\n @param user_uuid The id of the user\n @param user_name The name of the user\n @param user_status The status of the user (0: not connected; 1: connected)\n\n Commands:\n /user \"user_uuid\"\n /info"]
    pub fn client_print_user(
        user_uuid: *const ::std::os::raw::c_char,
        user_name: *const ::std::os::raw::c_char,
        user_status: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you requested an individual team\n ex: get the current used team\n @param team_uuid The id of the team\n @param team_name The name of the team\n @param team_description The description of the team\n\n Commands:\n /info"]
    pub fn client_print_team(
        team_uuid: *const ::std::os::raw::c_char,
        team_name: *const ::std::os::raw::c_char,
        team_description: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you requested an individual channel\n ex: get the current used channel\n @param channel_uuid The id of the channel\n @param channel_name The name of the channel\n @param channel_description The description of the channel\n\n Commands:\n /info"]
    pub fn client_print_channel(
        channel_uuid: *const ::std::os::raw::c_char,
        channel_name: *const ::std::os::raw::c_char,
        channel_description: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you requested an individual thread\n ex: get the current used thread\n @param thread_uuid The id of the thread\n @param user_uuid The id of the user who created the thread\n @param thread_timestamp The unix timestamp of the creation of the thread\n @param thread_title The title of the thread\n @param thread_body The body of the thread\n\n Commands:\n /info"]
    pub fn client_print_thread(
        thread_uuid: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
        thread_timestamp: time_t,
        thread_title: *const ::std::os::raw::c_char,
        thread_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you create a team successfully\n @param team_uuid The id of the team that was created\n @param team_name The name of the team that was created\n @param team_description The description of the team that was created\n\n Commands:\n /create \"team_name\" \"team_description\""]
    pub fn client_print_team_created(
        team_uuid: *const ::std::os::raw::c_char,
        team_name: *const ::std::os::raw::c_char,
        team_description: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you create channel successfully\n @param channel_uuid The id of the channel that was created\n @param channel_name The name of the channel that was created\n @param channel_description The description of the channel that was created\n\n Commands:\n /create \"channel_name\" \"channel_description\""]
    pub fn client_print_channel_created(
        channel_uuid: *const ::std::os::raw::c_char,
        channel_name: *const ::std::os::raw::c_char,
        channel_description: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you create a thread successfully\n @param thread_uuid The id of the thread that was created\n @param user_uuid The id of the user who created the thread\n @param thread_timestamp The unix timestamp of the thread creation\n @param thread_title The title of the thread that was created\n @param thread_body The body of the thread that was created\n\n Commands:\n /create \"thread_title\" \"thread_body\""]
    pub fn client_print_thread_created(
        thread_uuid: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
        thread_timestamp: time_t,
        thread_title: *const ::std::os::raw::c_char,
        thread_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you create a reply successfully\n @param thread_uuid The id of the thread this reply was created in\n @param user_uuid The id of the user who created the reply\n @param reply_timestamp The unix timestamp of the created reply\n @param reply_body The body of the created reply\n\n Commands:\n /create \"reply_body\""]
    pub fn client_print_reply_created(
        thread_uuid: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
        reply_timestamp: time_t,
        reply_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you subscribe to a team successfully\n @param user_uuid The id of the user who subscribed to the team\n @param team_uuid The id of the team the user subscribed to\n\n Commands:\n /subscribe \"team_uuid\""]
    pub fn client_print_subscribed(
        user_uuid: *const ::std::os::raw::c_char,
        team_uuid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when you unsubscribe from a team successfully\n @param user_uuid The id of the user who unsubscribed from the team\n @param team_uuid The id of the team the user unsubscribed from\n\n Commands:\n /unsubscribe \"team_uuid\""]
    pub fn client_print_unsubscribed(
        user_uuid: *const ::std::os::raw::c_char,
        team_uuid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a new team is created\n @param team_uuid The id of the team that was created\n @param team_name The name of the team that was created\n @param user_uuid The id of the user who created the new team\n\n Commands:\n /create \"team_name\" \"team_description\""]
    pub fn server_event_team_created(
        team_uuid: *const ::std::os::raw::c_char,
        team_name: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a new channel is created\n @param team_uuid The id of the team this channel is in\n @param channel_uuid The id of the created channel\n @param channel_name The name of the new channel\n\n Commands:\n /create \"channel_name\" \"channel_description\""]
    pub fn server_event_channel_created(
        team_uuid: *const ::std::os::raw::c_char,
        channel_uuid: *const ::std::os::raw::c_char,
        channel_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a new thread is created\n @param channel_uuid The id of the channel this thread was created in\n @param thread_uuid The id of the created thread\n @param user_uuid The id of the user who created the thread\n @param thread_title The title of the created thread\n @param thread_body The body of the created thread\n\n Commands:\n /create \"thread_title\" \"thread_body\""]
    pub fn server_event_thread_created(
        channel_uuid: *const ::std::os::raw::c_char,
        thread_uuid: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
        thread_title: *const ::std::os::raw::c_char,
        thread_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a new reply is created in a thread\n @param thread_uuid The id of the thread this message was created in\n @param user_uuid The id of the user who created the reply\n @param reply_body The body of the created reply\n\n Commands:\n /create \"reply_body\""]
    pub fn server_event_reply_created(
        thread_uuid: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
        reply_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a user subscribe to a team\n @param team_uuid The id of the subscribed team\n @param user_uuid The id of the subscribed user\n\n Commands:\n /subscribe \"team_uuid\""]
    pub fn server_event_user_subscribed(
        team_uuid: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a user unsubscribe from a team\n @param team_uuid The id of the unsubscribed team\n @param user_uuid The id of the unsubscribed user\n\n Commands:\n /unsubscribe \"team_uuid\""]
    pub fn server_event_user_unsubscribed(
        team_uuid: *const ::std::os::raw::c_char,
        user_uuid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a user didn't existed in save and was created\n @param user_uuid The id of the user that was created\n @param user_name The name of the user that was created\n\n Commands:\n /login \"user_name\""]
    pub fn server_event_user_created(
        user_uuid: *const ::std::os::raw::c_char,
        user_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a user was loaded from the save file\n Should be called at the start of the server once per user loaded\n It should display all users that were saved\n @param user_uuid The id of the saved user\n @param user_name The name of the saved user\n\n Commands:\n None, should be used at server start"]
    pub fn server_event_user_loaded(
        user_uuid: *const ::std::os::raw::c_char,
        user_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a user logged in\n @param user_uuid The id of the user that logged in\n\n Commands:\n /login"]
    pub fn server_event_user_logged_in(
        user_uuid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a user logged out\n @param user_uuid The id of the user that logged out\n\n Commands:\n /logout\n When a user lost connexion to the server"]
    pub fn server_event_user_logged_out(
        user_uuid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Must be called when a private message was sent between users\n @param sender_uuid The id of the user that sent the message\n @param receiver_uuid The if of the user that receive the message\n @param message_body The message body\n\n Commands:\n /send \"user_uuid\" \"message_body\""]
    pub fn server_event_private_message_sended(
        sender_uuid: *const ::std::os::raw::c_char,
        receiver_uuid: *const ::std::os::raw::c_char,
        message_body: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __locale_data {
    pub _address: u8,
}
