name: Rust Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build with Makefile
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lib
          make

      - name: Test
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lib
          cargo test
